version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.0.9
    - 10.1.3
  - dependency-name: sb
    versions:
    - 6.1.21
    - 6.2.2
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.21
    - 6.2.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.34
    - 14.14.35
  - dependency-name: eslint
    versions:
    - 7.22.0
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: next-pwa
    versions:
    - 5.0.6
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.21
  - dependency-name: husky
    versions:
    - 5.1.0
